# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 14.2.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run: bundle install

      - run:
          name: Install dependencies
          command: cd api/ && npm install

      - run:
          name: Install MongoDB
          command: |
            cd api/
            brew tap mongodb/brew
            brew update
            brew install mongodb-community@7.0
      - run:
          name: Start MongoDB service
          command: cd api/ && brew services start mongodb-community
      - run:
          name: Restore MongoDB backup
          command: cd api/ && mongorestore
      - run:
          name: Install NestJs
          command: cd api/ && npm i -g @nestjs/cli
      - run:
          name: Start API
          command: |
            cd api/
            npm run start:dev &
            # Attendre que l'API soit prête à recevoir des requêtes
            until $(curl --output /dev/null --silent --head --fail http://localhost:3000); do
                printf '.'
                sleep 1
            done
      - run:
          name: Fastlane
          command: cd IOS/EFD && bundle exec fastlane ios_test 
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  adhoc:
    macos:
      xcode: 14.2.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: adhoc
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output

workflows:
  build-test-adhoc:
    jobs:
      - build-and-test
      - adhoc:
          filters:
            branches:
              only: development
          requires:
            - build-and-test
