# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and test"
  lane :ios_test do
    begin
      scan(
        include_simulator_logs: false,
        scheme: "EFD",
        only_testing: "EFDTests",
        output_types: "html"
      )
    rescue => error
      UI.error("Une erreur s'est produite lors de l'exécution des tests : #{error.message}")
      raise error
    end
  end
end
